# Generated by Django 4.1.5 on 2023-01-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sherbimet',
            fields=[
                ('sherbimet_id', models.AutoField(primary_key=True, serialize=False)),
                ('sherbimet_image', models.ImageField(upload_to='sherbime/')),
                ('sherbimet_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sherbimet_description', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
