# Generated by Django 4.1.5 on 2023-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_mosha', models.IntegerField(blank=True, max_length=3, null=True)),
                ('contact_tel', models.IntegerField(blank=True, max_length=12, null=True)),
                ('contact_problema', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
